repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.62.0
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
    - id: terraform_docs
      args:
        - --args=--config=.terraform-docs.yml
